language: java
jdk:
  - openjdk8
services:
  - docker
script:
  - mvn clean install
deploy:
  # push docker image to docker hub
  - provider: script
    skip_cleanup: true
    script: >-
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker build -t $DOCKER_IMAGE .;
      docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$DOCKER_TAG;
      docker push $DOCKER_IMAGE;
    on:
      branch: master
env:
  global:
    - DOCKER_IMAGE=dianw/akinabot
    - DOCKER_TAG=2.0.0