version: '3'
services:
  akinabot:
    container_name: akinabot
    image: dianw/akinabot
    ports:
      - 8080:8080
    environment:
      TELEGRAM_TOKEN:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    depends_on:
      - akinabot
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
volumes:
  prometheus: