scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'akinabot'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['akinabot-server:8080']
  - job_name: 'hazelcast'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['akinabot-hazelcast:8080']