telegram:
  poll-rate: 500
  token:
  webhook: false
line:
  token: ''
  secret: ''
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
logging:
  level:
    com.linecorp: warn